spring:
  data.neo4j:
    embedded.enabled: false
    username: ${NEO4J_USER}
    password: ${NEO4J_PASSWORD}
    uri: bolt://${NEO4J_HOST:localhost}:${NEO4J_PORT:7687}
  messages:
    basename: i18n/messages

management:
  endpoints:
    web.base-path: /api/actuator
  endpoint:
    health:
      cache.time-to-live: 15s
      show-details: always
  health:
    diskspace.enabled: false

---

spring.profiles: production
server.port: 8080
logging.level:
  org.neo4j.ogm.drivers.bolt.request: WARN

---

spring.profiles: dev
server.port: 8181
logging.level:
  com.cloudbees.ce: DEBUG
spring:
  data.neo4j:
    username: neo4j
    password: plugin
